{% set name = "napari-bleach-correct" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-bleach-correct-{{ version }}.tar.gz
  sha256: 6f027173992b0607c52eac87e2074a3d407a447076052896e7e738db44f3f46a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - numpy
    - pyqtgraph
    - python >=3.8
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_bleach_correct
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marx-alex/napari-bleach-correct
  summary: A napari plugin to correct time-lapse images for photobleaching.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - marx-alex
